  - name: Start T01 Administration - Cloud Service Tests
    ansible.builtin.shell: npx playwright test ./tests/T01.spec.ts
    args:
      chdir: /opt/openstack-testing
    register: results
    ignore_errors: true
  - debug: msg="T01 Administration - Cloud Service Tests passed successfully"
      
  - name: Start T03 Administration - Compute / Storage Tests
    ansible.builtin.shell: npx playwright test ./tests/T03.spec.ts
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="T03 Administration - Compute / Storage Tests passed successfully"

  - name: Start T06 Openstack Nodes Functionality Tests
    ansible.builtin.shell: npx playwright test ./tests/T06.spec.ts
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="T06 Openstack Nodes Functionality Tests passed successfully"
      
  - name: Start T07 RHOSP Version Tests
    ansible.builtin.shell: npx playwright test ./tests/T07.spec.ts
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="T07 RHOSP Version Tests passed successfully"
      
  - name: Start T04 Infrastructure-Virtual Resources Tests
    ansible.builtin.shell: npx playwright test ./tests/T04.spec.ts
    args:
      chdir: /opt/openstack-testing
    register: results
    ignore_errors: true
  - debug: msg="T04 Infrastructure-Virtual Resources Tests passed successfully"
    
  - name: Allure generate results
    args:
      chdir: /opt/openstack-testing
    shell: |
      PATH=/opt/allure-commandline/allure-2.21.0/bin:$PATH
      allure generate allure-results --clean
    register: results
  - debug:
      var: results.stdout_lines
        
  - name: Allure generate report
    args:
      chdir: /opt/openstack-testing
    shell: |
      PATH=/opt/allure-commandline/allure-2.21.0/bin:$PATH
      node ./node_modules/allure-single-html-file-js/combine.js ./allure-report

  - name: Allure open allure-report
    args:
      chdir: /opt/openstack-testing
    shell: |
      PATH=/opt/allure-commandline/allure-2.21.0/bin:$PATH
      nohup allure serve -p 32300 &
